apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: app
          image: flaskapp:latest
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_HOST
              value: "db-service"
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: db_user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: db_pass
            - name: DATABASE_NAME
              value: "mydb"
